CREATE TABLE `Usuario` (
  `idUsuario` int NOT NULL AUTO_INCREMENT,
  `nome` varchar(500) NOT NULL,
  `email` varchar(100) NOT NULL,
  `senha` varchar(8) NOT NULL,
  `is_admin` tinyint NOT NULL DEFAULT '0',
  `curso` varchar(100) NOT NULL,
  `matricula` int NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE KEY `idUsuario_UNIQUE` (`idUsuario`),
  UNIQUE KEY `matrícula_UNIQUE` (`matricula`)
) ;

INSERT INTO Usuario(nome,email,senha,is_admin,curso,matricula) VALUES ('Priscila Silva', 'priscila@gmail.com', '12345678', true, 'Engenharia da Computacao', 12345678);
INSERT INTO Usuario(nome,email,senha,is_admin,curso,matricula) VALUES ('Victor Silva', 'victor@gmail.com', '12345678', false, 'Ciência da Computacao', 87654321);
INSERT INTO Usuario(nome,email,senha,is_admin,curso,matricula) VALUES ('Heitor Silva', 'heitor@gmail.com', '12345678', false, 'Ciência da Computacao', 14253687);

CREATE TABLE `Departamento` (
  `idDepartamento` int NOT NULL,
  `nome` varchar(1000) NOT NULL,
  PRIMARY KEY (`idDepartamento`)
);
INSERT INTO Departamento(idDepartamento,nome) VALUES (643,'CENTRO DE APOIO AO DESENVOLVIMENTO TECNOLÓGICO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (640,'CENTRO DE DESENVOLVIMENTO SUSTENTÁVEL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (314,'CENTRO DE EXCELÊNCIA EM TURISMO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (650,'CENTRO ESTUDOS AVANÇADOS MULTIDISCIPLIN - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (316,'CENTRO INTEGRADO ORDENAMENTO TERRITORIAL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1448,'CENTRO INTERNACIONAL DE BIOÉTICA E HUMANIDADES - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (677,'CENTRO UNB CERRADO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (130,'DECANATO DE ENSINO DE GRADUACAO / DEG - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (170,'DECANATO DE PÓS-GRADUAÇÃO / DPG - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (158,'DECANATO EXTENSÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (351,'DEPARTAMENTO DE AUDIOVISUAIS E PUBLICIDADE/DAP - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (345,'DEPARTAMENTO DE COMUNICAÇÃO ORGANIZACIONAL/COM - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (660,'DEPARTAMENTO DE DESIGN (11.01.01.14.04) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (449,'DEPARTAMENTO DE ENGENHARIA MECANICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (479,'DEPARTAMENTO DE ESTUDOS LATINO AMERICANO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (678,'DEPARTAMENTO DE FARMACIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (791,'DEPARTAMENTO DE GESTAO DE POLITICAS PUBL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (352,'DEPARTAMENTO DE JORNALISMO/JOR - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (518,'DEPARTAMENTO DE MATEMÁTICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (390,'DEPARTAMENTO DE MÉTODOS E TÉCNICAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (391,'DEPARTAMENTO DE POLÍTICAS PÚBLICAS E GESTÃO DA EDUCAÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (592,'DEPARTAMENTO DE PSICOLOGIA CLÍNICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (483,'DEPARTAMENTO DE SOCIOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (392,'DEPARTAMENTO DE TEORIA E FUNDAMENTOS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (327,'DEPTO ADMINISTRAÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (481,'DEPTO ANTROPOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (492,'DEPTO ARTES CÊNICAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (498,'DEPTO ARTES VISUAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (464,'DEPTO BIOLOGIA CELULAR - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (462,'DEPTO BOTÂNICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (333,'DEPTO CIÊNCIAS CONTÁBEIS ATUARIAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (508,'DEPTO CIÊNCIAS DA COMPUTAÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (466,'DEPTO CIÊNCIAS FISIOLÓGICAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (337,'DEPTO CIÊNCIAS INFORMAÇÃO DOCUMENTAÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (467,'DEPTO ECOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (548,'DEPTO ECONOMIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (422,'DEPTO ENFERMAGEM - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (437,'DEPTO ENGENHARIA CIVIL E AMBIENTAL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (760,'DEPTO ENGENHARIA DE PRODUCAO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (443,'DEPTO ENGENHARIA ELETRICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (433,'DEPTO ENGENHARIA FLORESTAL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (514,'DEPTO ESTATÍSTICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (552,'DEPTO FILOSOFIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (469,'DEPTO FITOPATOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (471,'DEPTO GENÉTICA E MORFOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (555,'DEPTO GEOGRAFIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (539,'DEPTO GEOLOGIA GERAL APLICADA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (541,'DEPTO GEOQUÍMICA E RECURSOS MINERAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (559,'DEPTO HISTÓRIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (578,'DEPTO LINGUISTICA, PORT. LING. CLASSICAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (574,'DEPTO LÍNGUAS ESTRANGEIRAS E TRADUÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (540,'DEPTO MINERALOGIA E PETROLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (495,'DEPTO MÚSICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (424,'DEPTO NUTRICAO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (427,'DEPTO ODONTOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (594,'DEPTO PROCESSOS PSICOLÓGICOS BÁSICOS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (360,'DEPTO PROJETOS EXPRES REPRES ARQ E URBAN - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (593,'DEPTO PSICOLOGIA ESCOLAR DESENVOLVIMENTO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (596,'DEPTO PSICOLOGIA SOCIAL E DO TRABALHO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (420,'DEPTO SAUDE COLETIVA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (563,'DEPTO SERVIÇO SOCIAL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (361,'DEPTO TECNOLOGIA ARQUITETURA URBANISMO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (362,'DEPTO TEORIA HISTORIA ARQUIT E URBANISM - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (580,'DEPTO TEORIA LITERÁRIA E LITERATURA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (472,'DEPTO ZOOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (410,'FACULDADE DE  CIÊNCIAS DA SAÚDE - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (363,'FACULDADE DE AGRONOMIA E MEDICINA VETERINÁRIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (353,'FACULDADE DE ARQUITETURA E URBANISMO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (672,'FACULDADE DE CEILÂNDIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (674,'FACULDADE DE CIÊNCIA DA INFORMAÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (343,'FACULDADE DE COMUNICAÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (370,'FACULDADE DE DIREITO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (381,'FACULDADE DE EDUCAÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (393,'FACULDADE DE EDUCAÇÃO FÍSICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (402,'FACULDADE DE MEDICINA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (666,'FACULDADE DE PLANALTINA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (429,'FACULDADE DE TECNOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (673,'FACULDADE DO GAMA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (323,'FACULDADE ECONOMIA,  ADMINISTRAÇÃO,  CONTABILIDADE E  GEST POL PÚBLICAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1201,'GRADUAÇÃO EM ADMINISTRAÇÃO - BACHARELADO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (288,'HOSP-HOSPITAL UNIVERSITÁRIO DE BRASÍLIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (485,'INSTITUTO DE ARTES - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (668,'INSTITUTO DE CIÊNCIA POLÍTICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (455,'INSTITUTO DE CIÊNCIAS BIOLÓGICAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (504,'INSTITUTO DE CIÊNCIAS EXATAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (544,'INSTITUTO DE CIÊNCIAS HUMANAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (473,'INSTITUTO DE CIÊNCIAS SOCIAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (524,'INSTITUTO DE FÍSICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (533,'INSTITUTO DE GEOCIÊNCIAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (567,'INSTITUTO DE LETRAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (583,'INSTITUTO DE PSICOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (610,'INSTITUTO DE QUÍMICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (669,'INSTITUTO DE RELAÇÕES INTERNACIONAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (542,'OBSERVATÓRIO SISMOLÓGICO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1080,'PARQUE CIENTÍFICO E TECNOLÓGICO DA UNB - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1615,'PARQUE DE INOVAÇÃO E SUSTENTABILIDADE DO AMBIENTE CONSTRUÍDO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1617,'PROGRAMA DE PÓS-GRADUAÇÃO EM ADMINISTRAÇÃO (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (664,'PROGRAMA DE PÓS-GRADUAÇÃO EM ADMINISTRAÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (853,'PROGRAMA DE PÓS-GRADUAÇÃO EM AGRONEGÓCIOS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (854,'PROGRAMA DE PÓS-GRADUAÇÃO EM AGRONOMIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (855,'PROGRAMA DE PÓS-GRADUAÇÃO EM ANTROPOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (927,'PROGRAMA DE PÓS-GRADUAÇÃO EM ARQUITETURA E URBANISMO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (842,'PROGRAMA DE PÓS-GRADUAÇÃO EM ARTES CÊNICAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (911,'PROGRAMA DE PÓS-GRADUAÇÃO EM ARTES VISUAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1491,'PROGRAMA DE PÓS-GRADUAÇÃO EM BIOLOGIA ANIMAL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1501,'PROGRAMA DE PÓS-GRADUAÇÃO EM BIOLOGIA MICROBIANA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1492,'PROGRAMA DE PÓS-GRADUAÇÃO EM BIOTECNOLOGIA E BIODIVERSIDADE - REDE PRÓ-CENTRO-OESTE - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (831,'PROGRAMA DE PÓS-GRADUAÇÃO EM BIOÉTICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1489,'PROGRAMA DE PÓS-GRADUAÇÃO EM BOTÂNICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (900,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIA POLÍTICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (995,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS AMBIENTAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (909,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS ANIMAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1488,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS BIOLÓGICAS (BIOLOGIA MOLECULAR) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (896,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS CONTÁBEIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (946,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS DA INFORMAÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (898,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS DA REABILITAÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (902,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS DA SAÚDE - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (988,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS DE MATERIAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (903,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS DO COMPORTAMENTO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (897,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS E TECNOLOGIAS EM SAÚDE - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (906,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS FARMACÊUTICAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (997,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS FLORESTAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (904,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS MECÂNICAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (845,'PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIAS MÉDICAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (840,'PROGRAMA DE PÓS-GRADUAÇÃO EM COMPUTAÇÃO APLICADA (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (841,'PROGRAMA DE PÓS-GRADUAÇÃO EM COMUNICAÇÃO/PPGCOM - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (929,'PROGRAMA DE PÓS-GRADUAÇÃO EM DESENVOLVIMENTO E COOPERAÇÃO INTERNACIONAL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1487,'PROGRAMA DE PÓS-GRADUAÇÃO EM DESENVOLVIMENTO SUSTENTÁVEL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (875,'PROGRAMA DE PÓS-GRADUAÇÃO EM DESIGN - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (914,'PROGRAMA DE PÓS-GRADUAÇÃO EM DIREITO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1505,'PROGRAMA DE PÓS-GRADUAÇÃO EM DIREITO, REGULAÇÃO E POLÍTICAS PÚBLICAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (916,'PROGRAMA DE PÓS-GRADUAÇÃO EM DIREITOS HUMANOS E CIDADANIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1490,'PROGRAMA DE PÓS-GRADUAÇÃO EM ECOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1619,'PROGRAMA DE PÓS-GRADUAÇÃO EM ECONOMIA (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1198,'PROGRAMA DE PÓS-GRADUAÇÃO EM ECONOMIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1620,'PROGRAMA DE PÓS-GRADUAÇÃO EM EDUCAÇÃO (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (977,'PROGRAMA DE PÓS-GRADUAÇÃO EM EDUCAÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1185,'PROGRAMA DE PÓS-GRADUAÇÃO EM EDUCAÇÃO EM CIÊNCIAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1625,'PROGRAMA DE PÓS-GRADUAÇÃO EM EDUCAÇÃO FÍSICA (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (910,'PROGRAMA DE PÓS-GRADUAÇÃO EM EDUCAÇÃO FÍSICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (843,'PROGRAMA DE PÓS-GRADUAÇÃO EM ENFERMAGEM - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (959,'PROGRAMA DE PÓS-GRADUAÇÃO EM ENGENHARIA BIOMÉDICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (949,'PROGRAMA DE PÓS-GRADUAÇÃO EM ENGENHARIA DE SISTEMAS ELETRÔNICOS E AUTOMAÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (948,'PROGRAMA DE PÓS-GRADUAÇÃO EM ENGENHARIA ELÉTRICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1186,'PROGRAMA DE PÓS-GRADUAÇÃO EM ENSINO DE CIÊNCIAS (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1506,'PROGRAMA DE PÓS-GRADUAÇÃO EM ENSINO DE FÍSICA (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1613,'PROGRAMA DE PÓS-GRADUAÇÃO EM ENSINO DE GEOGRAFIA EM REDE (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (876,'PROGRAMA DE PÓS-GRADUAÇÃO EM ESTATÍSTICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (829,'PROGRAMA DE PÓS-GRADUAÇÃO EM ESTRUTURAS E CONSTRUÇÃO CIVIL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1225,'PROGRAMA DE PÓS-GRADUAÇÃO EM ESTUDOS COMPARADOS SOBRE AS AMÉRICAS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1494,'PROGRAMA DE PÓS-GRADUAÇÃO EM ESTUDOS DA TRADUÇÃO - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1664,'PROGRAMA DE PÓS-GRADUAÇÃO EM FILOSOFIA (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (917,'PROGRAMA DE PÓS-GRADUAÇÃO EM FILOSOFIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (947,'PROGRAMA DE PÓS-GRADUAÇÃO EM FITOPATOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (985,'PROGRAMA DE PÓS-GRADUAÇÃO EM FÍSICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (932,'PROGRAMA DE PÓS-GRADUAÇÃO EM GEOCIÊNCIAS APLICADAS E GEODINÂMICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1493,'PROGRAMA DE PÓS-GRADUAÇÃO EM GEOGRAFIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (931,'PROGRAMA DE PÓS-GRADUAÇÃO EM GEOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (901,'PROGRAMA DE PÓS-GRADUAÇÃO EM GEOTECNIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1503,'PROGRAMA DE PÓS-GRADUAÇÃO EM GESTÃO E REGULAÇÃO DE RECURSOS HÍDRICOS - PROFÁGUA (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (933,'PROGRAMA DE PÓS-GRADUAÇÃO EM GESTÃO PÚBLICA (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1616,'PROGRAMA DE PÓS-GRADUAÇÃO EM GOVERNANÇA E INOVAÇÃO EM POLÍTICAS PÚBLICAS (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (928,'PROGRAMA DE PÓS-GRADUAÇÃO EM HISTÓRIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (895,'PROGRAMA DE PÓS-GRADUAÇÃO EM INFORMÁTICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (960,'PROGRAMA DE PÓS-GRADUAÇÃO EM INTEGRIDADE DE MATERIAIS DA ENGENHARIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1495,'PROGRAMA DE PÓS-GRADUAÇÃO EM LINGUÍSTICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1203,'PROGRAMA DE PÓS-GRADUAÇÃO EM LINGUÍSTICA APLICADA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (987,'PROGRAMA DE PÓS-GRADUAÇÃO EM LITERATURA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (983,'PROGRAMA DE PÓS-GRADUAÇÃO EM MATEMÁTICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (990,'PROGRAMA DE PÓS-GRADUAÇÃO EM MATEMÁTICA EM REDE NACIONAL (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (874,'PROGRAMA DE PÓS-GRADUAÇÃO EM MEDICINA TROPICAL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (996,'PROGRAMA DE PÓS-GRADUAÇÃO EM MEIO AMBIENTE EM DESENVOLVIMENTO RURAL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (926,'PROGRAMA DE PÓS-GRADUAÇÃO EM METAFÍSICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (873,'PROGRAMA DE PÓS-GRADUAÇÃO EM MÚSICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1502,'PROGRAMA DE PÓS-GRADUAÇÃO EM NANOCIÊNCIA E NANOBIOTECNOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (899,'PROGRAMA DE PÓS-GRADUAÇÃO EM NUTRIÇÃO HUMANA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (907,'PROGRAMA DE PÓS-GRADUAÇÃO EM ODONTOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1496,'PROGRAMA DE PÓS-GRADUAÇÃO EM PATOLOGIA MOLECULAR - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1499,'PROGRAMA DE PÓS-GRADUAÇÃO EM POLÍTICA SOCIAL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1624,'PROGRAMA DE PÓS-GRADUAÇÃO EM POLÍTICAS PÚBLICAS PARA INFÂNCIA E JUVENTUDE (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (982,'PROGRAMA DE PÓS-GRADUAÇÃO EM PROCESSOS DE DESENVOLVIMENTO HUMANO E SAÚDE - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1618,'PROGRAMA DE PÓS-GRADUAÇÃO EM PROFARTES (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1545,'PROGRAMA DE PÓS-GRADUAÇÃO EM PROFARTES - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (978,'PROGRAMA DE PÓS-GRADUAÇÃO EM PROFNIT - PROPRIEDADE INTELECTUAL E TRANSFERÊNCIA DE TECNOLOGIA PARA A INOVAÇÃO (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (986,'PROGRAMA DE PÓS-GRADUAÇÃO EM PSICOLOGIA CLÍNICA E CULTURA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1497,'PROGRAMA DE PÓS-GRADUAÇÃO EM PSICOLOGIA DO DESENVOLVIMENTO E ESCOLAR - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (913,'PROGRAMA DE PÓS-GRADUAÇÃO EM PSICOLOGIA SOCIAL, DO TRABALHO E DAS ORGANIZAÇÕES (PSTO) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (844,'PROGRAMA DE PÓS-GRADUAÇÃO EM QUÍMICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1622,'PROGRAMA DE PÓS-GRADUAÇÃO EM REDE NACIONAL PARA ENSINO DAS CIÊNCIAS AMBIENTAIS (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1546,'PROGRAMA DE PÓS-GRADUAÇÃO EM REDE NACIONAL PARA ENSINO DAS CIÊNCIAS AMBIENTAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1498,'PROGRAMA DE PÓS-GRADUAÇÃO EM RELAÇÕES INTERNACIONAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (872,'PROGRAMA DE PÓS-GRADUAÇÃO EM SAÚDE ANIMAL - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1623,'PROGRAMA DE PÓS-GRADUAÇÃO EM SAÚDE COLETIVA (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (908,'PROGRAMA DE PÓS-GRADUAÇÃO EM SAÚDE COLETIVA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (912,'PROGRAMA DE PÓS-GRADUAÇÃO EM SISTEMAS MECATRÔNICOS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (915,'PROGRAMA DE PÓS-GRADUAÇÃO EM SOCIOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1504,'PROGRAMA DE PÓS-GRADUAÇÃO EM SUSTENTABILIDADE JUNTO A POVOS E TERRITÓRIOS TRADICIONAIS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (830,'PROGRAMA DE PÓS-GRADUAÇÃO EM TECNOLOGIA AMBIENTAL E RECURSOS HÍDRICOS - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (930,'PROGRAMA DE PÓS-GRADUAÇÃO EM TECNOLOGIAS QUÍMICA E BIOLÓGICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (828,'PROGRAMA DE PÓS-GRADUAÇÃO EM TRANSPORTES - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1500,'PROGRAMA DE PÓS-GRADUAÇÃO EM ZOOLOGIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1543,'PROGRAMA DE PÓS-GRADUAÇÃO PROFBIO ENSINO DE BIOLOGIA EM REDE NACIONAL (PROFISSIONAL) - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (1621,'PROGRAMA DE PÓS-GRADUAÇÃO PROFISSIONAL EM ENGENHARIA ELÉTRICA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (69,'REITORIA - BRASÍLIA');
INSERT INTO Departamento(idDepartamento,nome) VALUES (140,'SECRETARIA DE ADMINISTRACAO ACADEMICA - BRASÍLIA');

CREATE TABLE `Disciplina` (
  `idDisciplina` varchar(20) NOT NULL,
  `nome` varchar(1000) NOT NULL,
  PRIMARY KEY (`idDisciplina`),
  UNIQUE KEY `idDisciplina_UNIQUE` (`idDisciplina`)
);
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CDT1101','TECNOLOGIA SOCIAL E INOVAÇÃO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CDS0004','AGRICULTURA E MEIO AMBIENTE');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CDS0007','INTRODUÇÃO AO DESENVOLVIMENTO SUSTENTÁVEL');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CDS0008','MEIO AMBIENTE, CULTURA E SOCIEDADE');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CDS0010','TRABALHO INTERDISCIPLINAR INTEGRADO 1');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CDS0011','SISTEMAS SOCIOAMBIENTAIS E COMPLEXIDADE');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CDS0012','POLÍTICAS PÚBLICAS E MEIO AMBIENTE');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CDS0013','POPULAÇÃO E MEIO AMBIENTE');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CDS0015','INDICADORES DE DESENVOLVIMENTO SUSTENTÁVEL');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CDS0019','PRÁTICA DE PESQUISA 1');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0001','PLANEJAMENTO E GESTÃO EM TURISMO 1');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0002','LEGISLAÇÃO TURÍSTICA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0005','PLANEJAMENTO E GESTÃO EM TURISMO 2');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0006','FUNDAMENTOS DE ESTATÍSTICA APLICADO AO TURISMO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0007','PROJETO INTEGRADOR EM TURISMO 3');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0012','ENOTURISMO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0013','PESQUISA EM TURISMO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0014','ESTRUTURAÇÃO E PROMOÇÃO DE DESTINOS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0015','SEMINÁRIOS EM TURISMO 3');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0022','ELABORAÇAO DE PROJETOS EM TURISMO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0032','SEMINÁRIOS EM TURISMO 4');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0036','SEMINÁRIOS EM TURISMO 6');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0037','SEMINÁRIOS EM TURISMO 7');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0038','ESTUDO DO TURISMO 1');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0039','SUSTENTABILIDADE ÉTICA E TURISMO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0040','ESTUDO DO TURISMO 2');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0041','CONSTRUÇÃO DO CONHECIMENTO CIENTÍFICO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0042','PROJETO INTEGRADOR EM TURISMO 1');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0043','ESTUDO DO TURISMO 3');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0044','COMUNICAÇÃO NO TURISMO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0045','ESTRUTURAS DE SUPORTE AO TURISMO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0046','SEMINÁRIOS EM TURISMO 1');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0050','EQUIPAMENTOS E SERVIÇOS TURÍSTICOS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0051','EQUIPAMENTOS E SERVIÇOS TURÍSTICOS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0052','EQUIPAMENTOS E SERVIÇOS TURISTICOS-AGENCIAMENTO OPERAÇÃO E TRANSPORTE');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0053','EQUIPAMENTOS E SERVIÇOS TURÍSTICOS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0054','EQUIPAMENTOS E SERVIÇOS TURÍSTICOS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CET0055','PROJETO INTEGRADOR EM TURISMO 2');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0005','METODOLOGIA E TÉCNICAS DE PESQUISA CIENTÍFICA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0007','ARTE E MANIFESTAÇÕES CULTURAIS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0008','BENS COMUNS, DIREITOS DA NATUREZA E CONFLITOS NA AMAZÔNIA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0009','GESTÃO E INOVAÇÃO DE PROCESSOS CRÍTICOS EM ORGANIZAÇÃO DE SERVIÇO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0015','UNIVERSIDADE, SOCIEDADE E ESTADO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0018','LAYA YOGA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0021','DIVERSIDADE SEXUAL E DE GÊNERO E POLÍTICAS PÚBLICAS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0030','MÓDULO 1');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0043','CULTURA PODER E RELAÇÕES RACIAIS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0047','TÓPICOS ESPECIAIS SOBRE A AMAZÔNIA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0051','PROMOÇÃO DA SAÚDE 3');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0054','INTRODUÇÃO A GESTÃO AMBIENTAL');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0058','DIREITOS DA CRIANCA E DO ADOLESCENTE');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0067','MULTICULTURALISMO E BUDISMO NA CONTEMPORANEIDADE');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0097','DIREITOS HUMANOS E CIDADANIA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0110','AGRICULTURA ALTERNATIVA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0125','HISTÓRIA E CINEMA: PERSPECTIVAS DOS FEMINISMOS NEGROS, DECOLONIAIS E INTERSECCIONAIS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0126','DIREITOS HUMANOS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0129','ESTUDOS DISCURSIVOS CRÍTICOS, CORPOS E INTERSECCIONALIDADES');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0131','RAÇA, CIÊNCIA E SAÚDE DA POPULAÇÃO NEGRA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0132','EXPERIÊNCIAS HISTÓRICAS DE REFORMA AGRÁRIA NO MUNDO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CEM0239','INTRODUÇÃO À HISTÓRIA DO PENSAMENTO ITALIANO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CBH0002','BIOÉTICA E BIOTECNOCIÊNCIAS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('CER0002','TÓPICOS EM ESTUDOS DO CERRADO 2');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DEG0229','PESQUISA CIENTÍFICA EM GRANDES TEMAS 1');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG0022','TEORIA QUÂNTICA 1');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG0229','PETROLOGIA DE ROCHAS GRANÍTICAS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG0308','POÉTICAS CONTEMPORÂNEAS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG0421','CONTROLE NÃO LINEAR');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG0568','ESTUDOS LABORATORIAIS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG0660','TREINAMENTO E DESENVOLVIMENTO DE PESSOAL');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG0675','MODELOS LINEARES GENERALIZADOS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG0849','FADIGA MULTIAXIAL');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG0928','MORFOLOGIA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG0942','INSTRUMENTAÇÃO EM BIOMECÂNICA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG1040','CATÁLISE HETEROGÊNEA: FUNDAMENTOS, ATUALIDADES E APLICAÇÕES');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG1046','GRUPOS PROFINITOS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG1165','TEORIA DOS GRUPOS FINITOS 2');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG1229','SEMINÁRIO DE PESQUISA EM EDUCAÇÃO AMBIENTAL I');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG1230','INTRODUÇÃO A SISTEMAS DE MATERIAIS NANOESTRUTURADOS');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG1231','SEMINÁRIO EM PSICOLOGIA DA SAÚDE 1');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG1232','INTRODUÇÃO À MECÂNICA DA FRATURA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG1233','LINGÚISTICA ANTROPOLÓGICA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DPG1237','TECNICAS NAO LINEARES EM CONTROLE');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DEX1102','PENSAMENTO NEGRO CONTEMPORÂNEO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DEX1104','CRIATIVIDADE E INTUIÇÃO NA PRODUÇÃO DO CONHECIMENTO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DEX1108','CONSTRUÇÃO DE PROJETOS SOCIAIS MULTIDISCIPLINARES');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DAP0008','ARGUMENTO E ROTEIRO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DAP0011','CRIATIVIDADE EM PUBLICIDADE');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DAP0021','CINEMA BRASILEIRO');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DAP0030','ADMINISTRAÇÃO PUBLICITÁRIA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DAP0042','DOCUMENTÁRIO 2');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DAP0044','PESQUISA PUBLICITÁRIA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DAP0055','FOTOGRAFIA E ILUMINACAO 2');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DAP0060','PUBLICIDADE E SOCIEDADE');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DAP0067','HISTORIA DO CINEMA');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DAP0076','FOTOGRAFIA E ILUMINAÇÃO 1');
INSERT INTO Disciplina(idDisciplina,nome) VALUES ('DAP0079','INTRODUÇÃO A FOTOGRAFIA');

CREATE TABLE `Professor` (
  `idProfessor` int NOT NULL AUTO_INCREMENT,
  `nome` varchar(500) NOT NULL,
  `idDepartamento` int NOT NULL,
  PRIMARY KEY (`idProfessor`),
  UNIQUE KEY `idProfessor_UNIQUE` (`idProfessor`),
  UNIQUE KEY `nome_UNIQUE` (`nome`),
  KEY `fk_id_departamento_idx` (`idDepartamento`),
  CONSTRAINT `fk_id_departamento` FOREIGN KEY (`idDepartamento`) REFERENCES `Departamento` (`idDepartamento`) ON DELETE CASCADE
);
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('TANIA CRISTINA DA SILVA CRUZ (30h)','643');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('JONATHAS FELIPE AIRES FERREIRA (30h)','643');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('LAURA ANGELICA FERREIRA DARNET (60h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MAURO GUILHERME MAIDANA CAPPELLARO (60h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MAURO GUILHERME MAIDANA CAPPELLARO (60h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('CRISTIANE GOMES BARRETO (60h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('LAURA ANGELICA FERREIRA DARNET (60h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('DORIS ALEIDA VILLAMIZAR SAYAGO (60h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ANA KARINE PEREIRA (30h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ANA KARINE PEREIRA (30h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('FREDERIC ADELIN GEORGES MERTENS (60h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ANA KARINE PEREIRA (60h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('STEPHANIE CAROLINE NASUTI (60h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('SAULO RODRIGUES PEREIRA FILHO (60h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MAURICIO DE CARVALHO AMAZONAS (60h)','640');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MARIANA TOMAZIN (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('AYLANA LAISSA MEDEIROS BORGES (30h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MARIANA TOMAZIN (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('JEFFERSON LORENCINI GAZONI (30h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MARUTSCHKA MARTINI MOESCH (30h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ALESSANDRA SANTOS DOS SANTOS (30h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('CAROLINA MENEZES PALHARES (30h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MARUTSCHKA MARTINI MOESCH (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('FAGNO TAVARES DE OLIVEIRA (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MARIANA TOMAZIN (30h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('JOAO PAULO FARIA TASSO (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('AYLANA LAISSA MEDEIROS BORGES (30h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('NEUZA DE FARIAS ARAUJO (30h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('NEUZA DE FARIAS ARAUJO (30h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('THIAGO SEBASTIANO DE MELO (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('JOAO PAULO FARIA TASSO (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('FAGNO TAVARES DE OLIVEIRA (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ANGELA TEBERGA DE PAULA (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('LANA MAGALY PIRES (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('NEUZA DE FARIAS ARAUJO (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MARIANA TOMAZIN (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ANA ROSA DOMINGUES DOS SANTOS (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('LUIZ CARLOS SPILLER PENA (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('EUZAMARA DE CARVALHO (15h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('THIAGO SEBASTIANO DE MELO (15h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ANGELA TEBERGA DE PAULA (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('THIAGO SEBASTIANO DE MELO (30h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ANGELA TEBERGA DE PAULA (30h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('AYLANA LAISSA MEDEIROS BORGES (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ANA ROSA DOMINGUES DOS SANTOS (60h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('THIAGO SEBASTIANO DE MELO (30h)','314');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('LUIZ FERNANDO MACEDO BESSA (5h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('JOÃO LUIZ HOMEM DE CARVALHO (30h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MARIO LIMA BRASIL (5h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('HILTON PEREIRA DA SILVA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('CELIA KINUKO MATSUNAGA HIGAWA (15h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MARISA COBBE MAASS (15h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MANOEL PEREIRA DE ANDRADE (5h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('FELÍCIO DE ARAÚJO PONTES JUNIOR (5h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ELA WIECKO VOLKMER DE CASTILHO (15h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('GILNEY AMORIM VIANA (5h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('GUILLERMO JOSE ASPER Y VALDES (30h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MURILO SILVA DE CAMARGO (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MURILO SILVA DE CAMARGO (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('NADIR HILGER (30h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('VIVIANE DE MELO RESENDE (30h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('VIVIANE DE MELO RESENDE (30h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('NADIR HILGER (30h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('NADIR HILGER (30h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('SILVIA BADIM MARQUES (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('LUCAS BRITO DE LIMA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('Tony Gigliotti Bezerra (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('PATRICIA CRISTINA DA SILVA PINHEIRO (0h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('CELI NELZA ZULKE TAFFAREL (0h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ADALBERTO DE SALLES LIMA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ENAILE DO ESPIRITO SANTO IADANZA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MAGNO ANTONIO MATAMOROS BURGOS (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('HILTON PEREIRA DA SILVA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MANOEL PEREIRA DE ANDRADE (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('TAYANE MEDEIROS DE OLIVEIRA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('CASSIO MURILO ALVES COSTA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('JONATAS DE FRANCA BARROS (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('RAUL LUÍS DE MELO DUSI (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ISAIAS NERY FERREIRA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('JACKELINE NERES BELLUCCI (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ANDRE RIBEIRO DA SILVA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('FELIPE SILVA BELLUCCI (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('JITONE LEONIDAS SOARES (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ANDREA DE OLIVEIRA GONCALVES (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ALESSANDRA LISBOA DA SILVA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('FERNANDO PAIVA SCARDUA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ASSIS DA COSTA OLIVEIRA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MARCIA GUEDES VIEIRA (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('ROMULO GUILHERME FERREIRA DA SILVA (20h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('RAFAELA ROCHA FEIJÓ (20h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('PAULO RAMOS COELHO FILHO (20h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('VANNESSA ALVES CARNEIRO (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('JOÃO LUIZ HOMEM DE CARVALHO (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MANOEL PEREIRA DE ANDRADE (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('RENATA MELO BARBOSA DO NASCIMENTO (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('TATIANE DOS SANTOS DUARTE (30h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MARIA CARMEN AIRES GOMES (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('MARJORIE NOGUEIRA CHAVES (60h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('CLARICE APARECIDA DOS SANTOS (15h)','650');
INSERT IGNORE INTO Professor(nome,idDepartamento) VALUES ('LUIS ANTONIO PASQUETTI (15h)','650');

CREATE TABLE `Turma` (
  `idTurma` int NOT NULL AUTO_INCREMENT,
  `numeroTurma` varchar(3) NOT NULL,
  `periodo` varchar(20) NOT NULL,
  `codDisciplinaTurma` varchar(20) NOT NULL,
  `codProfessorTurma` int NOT NULL,
  PRIMARY KEY (`idTurma`),
  UNIQUE KEY `idTurma_UNIQUE` (`idTurma`),
  KEY `fk_TurmaProfessor_2_idx` (`codProfessorTurma`),
  KEY `fk_TurmaDisciplina_1_idx` (`codDisciplinaTurma`),
  CONSTRAINT `fk_TurmaDisciplina_1` FOREIGN KEY (`codDisciplinaTurma`) REFERENCES `Disciplina` (`idDisciplina`) ON DELETE CASCADE,
  CONSTRAINT `fk_TurmaProfessor_2` FOREIGN KEY (`codProfessorTurma`) REFERENCES `Professor` (`idProfessor`) ON DELETE CASCADE
);

INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDT1101','1',20221,(SELECT idProfessor from Professor where nome = 'TANIA CRISTINA DA SILVA CRUZ (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDT1101','1',20221,(SELECT idProfessor from Professor where nome = 'JONATHAS FELIPE AIRES FERREIRA (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0004','1',20221,(SELECT idProfessor from Professor where nome = 'LAURA ANGELICA FERREIRA DARNET (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0007','1',20221,(SELECT idProfessor from Professor where nome = 'MAURO GUILHERME MAIDANA CAPPELLARO (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0007','2',20221,(SELECT idProfessor from Professor where nome = 'MAURO GUILHERME MAIDANA CAPPELLARO (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0007','4',20221,(SELECT idProfessor from Professor where nome = 'CRISTIANE GOMES BARRETO (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0007','5',20221,(SELECT idProfessor from Professor where nome = 'LAURA ANGELICA FERREIRA DARNET (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0008','1',20221,(SELECT idProfessor from Professor where nome = 'DORIS ALEIDA VILLAMIZAR SAYAGO (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0010','1',20221,(SELECT idProfessor from Professor where nome = 'ANA KARINE PEREIRA (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0010','2',20221,(SELECT idProfessor from Professor where nome = 'ANA KARINE PEREIRA (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0011','1',20221,(SELECT idProfessor from Professor where nome = 'FREDERIC ADELIN GEORGES MERTENS (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0012','1',20221,(SELECT idProfessor from Professor where nome = 'ANA KARINE PEREIRA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0013','1',20221,(SELECT idProfessor from Professor where nome = 'STEPHANIE CAROLINE NASUTI (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0015','1',20221,(SELECT idProfessor from Professor where nome = 'SAULO RODRIGUES PEREIRA FILHO (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CDS0019','1',20221,(SELECT idProfessor from Professor where nome = 'MAURICIO DE CARVALHO AMAZONAS (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0001','1',20221,(SELECT idProfessor from Professor where nome = 'MARIANA TOMAZIN (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0002','1',20221,(SELECT idProfessor from Professor where nome = 'AYLANA LAISSA MEDEIROS BORGES (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0005','1',20221,(SELECT idProfessor from Professor where nome = 'MARIANA TOMAZIN (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0006','1',20221,(SELECT idProfessor from Professor where nome = 'JEFFERSON LORENCINI GAZONI (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0007','1',20221,(SELECT idProfessor from Professor where nome = 'MARUTSCHKA MARTINI MOESCH (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0012','1',20221,(SELECT idProfessor from Professor where nome = 'ALESSANDRA SANTOS DOS SANTOS (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0012','1',20221,(SELECT idProfessor from Professor where nome = 'CAROLINA MENEZES PALHARES (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0013','1',20221,(SELECT idProfessor from Professor where nome = 'MARUTSCHKA MARTINI MOESCH (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0014','1',20221,(SELECT idProfessor from Professor where nome = 'FAGNO TAVARES DE OLIVEIRA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0015','1',20221,(SELECT idProfessor from Professor where nome = 'MARIANA TOMAZIN (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0022','1',20221,(SELECT idProfessor from Professor where nome = 'JOAO PAULO FARIA TASSO (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0032','1',20221,(SELECT idProfessor from Professor where nome = 'AYLANA LAISSA MEDEIROS BORGES (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0036','1',20221,(SELECT idProfessor from Professor where nome = 'NEUZA DE FARIAS ARAUJO (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0037','1',20221,(SELECT idProfessor from Professor where nome = 'NEUZA DE FARIAS ARAUJO (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0038','1',20221,(SELECT idProfessor from Professor where nome = 'THIAGO SEBASTIANO DE MELO (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0039','1',20221,(SELECT idProfessor from Professor where nome = 'JOAO PAULO FARIA TASSO (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0040','1',20221,(SELECT idProfessor from Professor where nome = 'FAGNO TAVARES DE OLIVEIRA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0041','1',20221,(SELECT idProfessor from Professor where nome = 'ANGELA TEBERGA DE PAULA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0041','1',20221,(SELECT idProfessor from Professor where nome = 'LANA MAGALY PIRES (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0042','1',20221,(SELECT idProfessor from Professor where nome = 'NEUZA DE FARIAS ARAUJO (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0043','1',20221,(SELECT idProfessor from Professor where nome = 'MARIANA TOMAZIN (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0044','1',20221,(SELECT idProfessor from Professor where nome = 'ANA ROSA DOMINGUES DOS SANTOS (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0045','1',20221,(SELECT idProfessor from Professor where nome = 'LUIZ CARLOS SPILLER PENA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0046','1',20221,(SELECT idProfessor from Professor where nome = 'EUZAMARA DE CARVALHO (15h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0046','1',20221,(SELECT idProfessor from Professor where nome = 'THIAGO SEBASTIANO DE MELO (15h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0050','1',20221,(SELECT idProfessor from Professor where nome = 'ANGELA TEBERGA DE PAULA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0051','1',20221,(SELECT idProfessor from Professor where nome = 'THIAGO SEBASTIANO DE MELO (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0052','1',20221,(SELECT idProfessor from Professor where nome = 'ANGELA TEBERGA DE PAULA (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0053','1',20221,(SELECT idProfessor from Professor where nome = 'AYLANA LAISSA MEDEIROS BORGES (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0054','1',20221,(SELECT idProfessor from Professor where nome = 'ANA ROSA DOMINGUES DOS SANTOS (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CET0055','1',20221,(SELECT idProfessor from Professor where nome = 'THIAGO SEBASTIANO DE MELO (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0005','1',20221,(SELECT idProfessor from Professor where nome = 'LUIZ FERNANDO MACEDO BESSA (5h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0005','1',20221,(SELECT idProfessor from Professor where nome = 'JOÃO LUIZ HOMEM DE CARVALHO (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0007','1',20221,(SELECT idProfessor from Professor where nome = 'MARIO LIMA BRASIL (5h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0007','1',20221,(SELECT idProfessor from Professor where nome = 'HILTON PEREIRA DA SILVA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0007','1',20221,(SELECT idProfessor from Professor where nome = 'CELIA KINUKO MATSUNAGA HIGAWA (15h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0007','1',20221,(SELECT idProfessor from Professor where nome = 'MARISA COBBE MAASS (15h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0008','1',20221,(SELECT idProfessor from Professor where nome = 'MANOEL PEREIRA DE ANDRADE (5h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0008','1',20221,(SELECT idProfessor from Professor where nome = 'FELÍCIO DE ARAÚJO PONTES JUNIOR (5h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0008','1',20221,(SELECT idProfessor from Professor where nome = 'ELA WIECKO VOLKMER DE CASTILHO (15h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0008','1',20221,(SELECT idProfessor from Professor where nome = 'GILNEY AMORIM VIANA (5h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0009','1',20221,(SELECT idProfessor from Professor where nome = 'GUILLERMO JOSE ASPER Y VALDES (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0015','1',20221,(SELECT idProfessor from Professor where nome = 'MURILO SILVA DE CAMARGO (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0015','2',20221,(SELECT idProfessor from Professor where nome = 'MURILO SILVA DE CAMARGO (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0018','1',20221,(SELECT idProfessor from Professor where nome = 'NADIR HILGER (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0018','3',20221,(SELECT idProfessor from Professor where nome = 'VIVIANE DE MELO RESENDE (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0018','4',20221,(SELECT idProfessor from Professor where nome = 'VIVIANE DE MELO RESENDE (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0018','6',20221,(SELECT idProfessor from Professor where nome = 'NADIR HILGER (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0018','8',20221,(SELECT idProfessor from Professor where nome = 'NADIR HILGER (30h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0021','1',20221,(SELECT idProfessor from Professor where nome = 'SILVIA BADIM MARQUES (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0021','1',20221,(SELECT idProfessor from Professor where nome = 'LUCAS BRITO DE LIMA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0021','1',20221,(SELECT idProfessor from Professor where nome = 'Tony Gigliotti Bezerra (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0030','1',20221,(SELECT idProfessor from Professor where nome = 'PATRICIA CRISTINA DA SILVA PINHEIRO (0h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0030','1',20221,(SELECT idProfessor from Professor where nome = 'CELI NELZA ZULKE TAFFAREL (0h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0043','1',20221,(SELECT idProfessor from Professor where nome = 'ADALBERTO DE SALLES LIMA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0047','1',20221,(SELECT idProfessor from Professor where nome = 'ENAILE DO ESPIRITO SANTO IADANZA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0047','1',20221,(SELECT idProfessor from Professor where nome = 'MAGNO ANTONIO MATAMOROS BURGOS (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0047','1',20221,(SELECT idProfessor from Professor where nome = 'HILTON PEREIRA DA SILVA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0047','1',20221,(SELECT idProfessor from Professor where nome = 'MANOEL PEREIRA DE ANDRADE (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0051','1',20221,(SELECT idProfessor from Professor where nome = 'TAYANE MEDEIROS DE OLIVEIRA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0051','1',20221,(SELECT idProfessor from Professor where nome = 'CASSIO MURILO ALVES COSTA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0051','1',20221,(SELECT idProfessor from Professor where nome = 'JONATAS DE FRANCA BARROS (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0051','1',20221,(SELECT idProfessor from Professor where nome = 'RAUL LUÍS DE MELO DUSI (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0051','1',20221,(SELECT idProfessor from Professor where nome = 'ISAIAS NERY FERREIRA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0051','1',20221,(SELECT idProfessor from Professor where nome = 'JACKELINE NERES BELLUCCI (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0051','1',20221,(SELECT idProfessor from Professor where nome = 'ANDRE RIBEIRO DA SILVA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0051','1',20221,(SELECT idProfessor from Professor where nome = 'FELIPE SILVA BELLUCCI (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0051','1',20221,(SELECT idProfessor from Professor where nome = 'JITONE LEONIDAS SOARES (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0051','1',20221,(SELECT idProfessor from Professor where nome = 'ANDREA DE OLIVEIRA GONCALVES (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0051','1',20221,(SELECT idProfessor from Professor where nome = 'ALESSANDRA LISBOA DA SILVA (60h)'));
INSERT INTO Turma(codDisciplinaTurma,numeroTurma,periodo,codProfessorTurma) VALUES ('CEM0054','1',20221,(SELECT idProfessor from Professor where nome = 'FERNANDO PAIVA SCARDUA (60h)'));

CREATE TABLE `AvaliacaoProfessor` (
  `idAvaliacaoProfessor` int NOT NULL AUTO_INCREMENT,
  `comentario` varchar(120) DEFAULT NULL,
  `classificacao` int NOT NULL,
  `codProfessorAvaliado` int NOT NULL,
  `codUsuarioAvaliacao` int NOT NULL,
  PRIMARY KEY (`idAvaliacaoProfessor`),
  UNIQUE KEY `idAvaliacaoProfessor_UNIQUE` (`idAvaliacaoProfessor`),
  KEY `fk_id_professor_idx` (`codProfessorAvaliado`),
  KEY `fk_id_usuario_idx` (`codUsuarioAvaliacao`),
  CONSTRAINT `fk_AvaliacaoProfessor_1` FOREIGN KEY (`codProfessorAvaliado`) REFERENCES `Professor` (`idProfessor`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fk_AvaliacaoProfessor_2` FOREIGN KEY (`codUsuarioAvaliacao`) REFERENCES `Usuario` (`idUsuario`) ON DELETE CASCADE
);

INSERT INTO AvaliacaoProfessor(comentario,classificacao,codProfessorAvaliado,codUsuarioAvaliacao) VALUES ('Professor é ótimo',5,1,1);
INSERT INTO AvaliacaoProfessor(comentario,classificacao,codProfessorAvaliado,codUsuarioAvaliacao) VALUES ('Professor é médio',3,2,2);
INSERT INTO AvaliacaoProfessor(classificacao,codProfessorAvaliado,codUsuarioAvaliacao) VALUES (5,3,3);

CREATE TABLE `AvaliacaoTurma` (
  `idAvaliacaoTurma` int NOT NULL AUTO_INCREMENT,
  `comentario` varchar(120) DEFAULT NULL,
  `classificacao` int NOT NULL,
  `codTurmaAvaliada` int NOT NULL,
  `codUsuarioAvaliacao` int NOT NULL,
  PRIMARY KEY (`idAvaliacaoTurma`),
  UNIQUE KEY `idAvaliacaoTurma_UNIQUE` (`idAvaliacaoTurma`),
  KEY `fk_TurmaAvaliacaoTurma_1_idx` (`codTurmaAvaliada`),
  KEY `fk_UsuarioAvaliacaoTurma_2_idx` (`codUsuarioAvaliacao`),
  CONSTRAINT `fk_TurmaAvaliacaoTurma_1` FOREIGN KEY (`codTurmaAvaliada`) REFERENCES `Turma` (`idTurma`) ON DELETE CASCADE,
  CONSTRAINT `fk_UsuarioAvaliacaoTurma_2` FOREIGN KEY (`codUsuarioAvaliacao`) REFERENCES `Usuario` (`idUsuario`) ON DELETE CASCADE
);

INSERT INTO AvaliacaoTurma(comentario,classificacao,codTurmaAvaliada,codUsuarioAvaliacao) VALUES ('Disciplina muito boa',5,1,1);
INSERT INTO AvaliacaoTurma(comentario,classificacao,codTurmaAvaliada,codUsuarioAvaliacao) VALUES ('Disciplina muito puxada',3,2,2);
INSERT INTO AvaliacaoTurma(classificacao,codTurmaAvaliada,codUsuarioAvaliacao) VALUES (5,3,3);

CREATE TABLE `DenunciaProfessor` (
  `idDenunciaProfessor` int NOT NULL AUTO_INCREMENT,
  `comentario` varchar(120) NOT NULL,
  `status` tinyint NOT NULL,
  `codAvaliacaoProfessorDenuncia` int NOT NULL,
  `codUsuarioDenunciaProfessor` int NOT NULL,
  PRIMARY KEY (`idDenunciaProfessor`),
  UNIQUE KEY `idDenunciaProfessor_UNIQUE` (`idDenunciaProfessor`),
  KEY `fk_AvaliacaoDenunciaProfessor_1_idx` (`codAvaliacaoProfessorDenuncia`),
  KEY `fk_DenunciaProfessor_1_idx` (`codUsuarioDenunciaProfessor`),
  CONSTRAINT `fk_AvaliacaoDenunciaProfessor_1` FOREIGN KEY (`codAvaliacaoProfessorDenuncia`) REFERENCES `AvaliacaoProfessor` (`idAvaliacaoProfessor`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fk_DenunciaProfessor_2` FOREIGN KEY (`codUsuarioDenunciaProfessor`) REFERENCES `Usuario` (`idUsuario`)
);

INSERT INTO DenunciaProfessor(comentario,status,codAvaliacaoProfessorDenuncia,codUsuarioDenunciaProfessor) VALUES ('Comentario ofensivo',false,1,1);
INSERT INTO DenunciaProfessor(comentario,status,codAvaliacaoProfessorDenuncia,codUsuarioDenunciaProfessor) VALUES ('Comentario ofensivo',false,2,2);
INSERT INTO DenunciaProfessor(comentario,status,codAvaliacaoProfessorDenuncia,codUsuarioDenunciaProfessor) VALUES ('Comentario ofensivo',false,3,3);

CREATE TABLE `DenunciaTurma` (
  `idDenunciaTurma` int NOT NULL AUTO_INCREMENT,
  `comentario` varchar(120) NOT NULL,
  `status` tinyint NOT NULL,
  `codDenunciaTurmaAvaliacao` int NOT NULL,
  `codUsuarioDenunciaTurma` int NOT NULL,
  PRIMARY KEY (`idDenunciaTurma`),
  UNIQUE KEY `idDenunciaTurma_UNIQUE` (`idDenunciaTurma`),
  KEY `fk_DenunciaTurmaAvaliacao_1_idx` (`codDenunciaTurmaAvaliacao`),
  KEY `fk_DenunciaTurma_2_idx` (`codUsuarioDenunciaTurma`),
  CONSTRAINT `fk_DenunciaTurma_1` FOREIGN KEY (`codDenunciaTurmaAvaliacao`) REFERENCES `AvaliacaoTurma` (`idAvaliacaoTurma`) ON DELETE CASCADE,
  CONSTRAINT `fk_DenunciaTurma_2` FOREIGN KEY (`codUsuarioDenunciaTurma`) REFERENCES `Usuario` (`idUsuario`) ON DELETE CASCADE
);
INSERT INTO DenunciaTurma(comentario,status,codDenunciaTurmaAvaliacao,codUsuarioDenunciaTurma) VALUES ('Comentario ofensivo',false,1,1);
INSERT INTO DenunciaTurma(comentario,status,codDenunciaTurmaAvaliacao,codUsuarioDenunciaTurma) VALUES ('Comentario ofensivo',false,2,2);
INSERT INTO DenunciaTurma(comentario,status,codDenunciaTurmaAvaliacao,codUsuarioDenunciaTurma) VALUES ('Comentario ofensivo',false,3,3);

CREATE VIEW `turmaDisciplina` AS select `t`.`idTurma` AS `idTurma`,`t`.`periodo` AS `periodo`,`t`.`numeroTurma` AS `numeroTurma`,`dis`.`nome` AS `nome` from (`avaliacaoUnB`.`Turma` `t` left join `avaliacaoUnB`.`Disciplina` `dis` on((`t`.`codDisciplinaTurma` = `dis`.`idDisciplina`)));